name: smart_routine
description: SmartRoutine habit tracker app built with Flutter.
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=2.19.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.1.1
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  uuid: ^4.2.1
  google_fonts: ^6.1.0
  fl_chart: ^0.66.0
  flutter_animate: ^4.5.0
  flutter_local_notifications: ^18.0.0
  intl: ^0.19.0
  timezone: ^0.9.4
  path_provider: ^2.1.0
  firebase_core: ^2.24.2
  cloud_firestore: ^4.14.0
  firebase_auth: ^4.16.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.6
  hive_generator: ^2.0.1

flutter:
  uses-material-design: true
